name: PR Validation

on:
  pull_request:
    branches: [main]

jobs:
  detekt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Cache Detekt
        uses: actions/cache@v3
        with:
          path: |
            .detekt
            build/reports/detekt
          key: ${{ runner.os }}-detekt-${{ hashFiles('config/detekt.yml') }}

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Run Detekt
        run: ./gradlew detekt --no-daemon

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Generate models by Open Api
        run: ./gradlew openApiGenerate

      - name: Build project
        run: ./gradlew build
